export const DEFAULT_REMINDER_INTERVAL_DAYS = 8;
export const BACKUP_OVERDUE_THRESHOLD_DAYS = 7;
export const OTP_EXPIRY_SECONDS = 300; // 5 minutes
export const OTP_RESEND_COOLDOWN_SECONDS = 30;
export const MAX_OTP_ATTEMPTS = 5;

export const ROLES = {
  OWNER: 'Owner',
  STAFF: 'Staff',
  CUSTOMER: 'Customer',
} as const;

export type UserRole = (typeof ROLES)[keyof typeof ROLES];

export const ERROR_CODES = {
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  DUPLICATE_PHONE: 'DUPLICATE_PHONE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  OTP_EXPIRED: 'OTP_EXPIRED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;
